# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Microchip Technology
title: Harmony 3 Motor Control 
lang: en-US
timezone: America/Phoenix

description: Harmony 3 Motor Control package
url: "https://microchip-mplab-harmony.github.io"
baseurl: "/motor_control"
remote_theme: "Microchip-MPLAB-Harmony/just-the-docs@mchp-harmony"

# Build settings

# GH Pages default (to ensure local build is same)
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

markdown: kramdown

plugins:
  - jekyll-coffeescript                # GH Pages default (to ensure local build is same)
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-seo-tag                     # MCHP

#
# ------------ Theme configuration ------------
#

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Google Analytics Tracking (optional)
ga_tracking: UA-2724382-16

exclude:
  - "*.xml"
  - "*.py"
  - "*.ftl"
  - "*.c"
  - "*.h"
  - "*.X"
  - "*.IAR"
  - "Gem*"
  - "*.S"
  - "*.ld"
  - "*.jar"
  - "*.prj"

# Aux links for the upper right navigation
aux_links:
#  "See me on GitHub":
#  "{% octicon mark-github %}":
#    - "//github.com/Microchip-MPLAB-Harmony/aerospace"
  "Obtain Support from Microchip":
    - "https://support.microchip.com"

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/vendor/microchip_mplab_harmony_logo_150_transparent.png"

# Footer content appears at the bottom of every page's main content
footer_content: "<img src='https://raw.githubusercontent.com/wiki/Microchip-MPLAB-Harmony/Microchip-MPLAB-Harmony.github.io/images/microchip_logo.png' /><br />Copyright &copy; 2020 Microchip Technology."
