package:
  format-version: "1.0.0"
  name: "motor_control"
  type: "api"
  status: "production"
  required: true
  version: "3.10.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.17.0"
    - name: "x2c"
      type: "package"
      version: "v1.4.0"
    - name: "bsp"
      type: "package"
      version: "v3.16.1" 
    - name: "harmony-services"
      type: "package"
      version: "v1.3.1" 