package:
  format-version: "1.0.0"
  name: "motor_control"
  type: "api"
  status: "production"
  required: true
  version: "3.9.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.17.0"
    - name: "x2c"
      type: "package"
      version: "x2c_scope_update"
    - name: "bsp"
      type: "package"
      version: "bsp_fix" 