package:
  format-version: "1.0.0"
  name: "motor_control"
  version: "v3.11.0"
  type: "api"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.19.7"
    - name: "x2c"
      type: "package"
      version: "v1.5.0"
    - name: "bsp"
      type: "package"
      version: "v3.21.0" 
    - name: "harmony-services"
      type: "package"
      version: "v1.5.0" 