format_version: v1.0
type: UniqueComponent
attributes: {id: adc1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ADC_CALLBACK_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_CallbackRegister}
  - type: String
    attributes: {id: ADC_CHANNEL_SELECT_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_ChannelSelect}
  - type: String
    attributes: {id: ADC_CH_PHASE_U}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC_POSINPUT_AIN0}
  - type: String
    attributes: {id: ADC_CH_PHASE_V}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC_POSINPUT_AIN0}
  - type: String
    attributes: {id: ADC_CH_POT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC_POSINPUT_AIN0}
  - type: String
    attributes: {id: ADC_CH_VDC_BUS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC_POSINPUT_AIN14}
  - type: Combo
    attributes: {id: ADC_CONV_TRIGGER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: Free Run}
  - type: KeyValueSet
    attributes: {id: ADC_CTRLA_PRESCALER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: ADC_CTRLA_SLAVEEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADC_CTRLB_RESSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: '0'}
  - type: String
    attributes: {id: ADC_GET_RESULT_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_ConversionResultGet}
  - type: String
    attributes: {id: ADC_GND}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC_NEGINPUT_GND}
  - type: KeyValueSet
    attributes: {id: ADC_INPUTCTRL_MUXPOS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: '0'}
  - type: Boolean
    attributes: {id: ADC_INTENSET_RESRDY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: 'false'}
  - type: String
    attributes: {id: ADC_INT_CLEAR_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_InterruptsClear}
  - type: String
    attributes: {id: ADC_INT_DISABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_InterruptsDisable}
  - type: String
    attributes: {id: ADC_INT_ENABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_InterruptsEnable}
  - type: String
    attributes: {id: ADC_IS_RESULT_READY_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_ConversionStatusGet}
  - type: Comment
    attributes: {id: ADC_SAMPCTRL_SAMPLEN_TIME}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Conversion Time is 2.13333333333 uS ****'}
  - type: String
    attributes: {id: ADC_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_Enable}
  - type: String
    attributes: {id: ADC_START_CONV_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_ConversionStart}
  - type: String
    attributes: {id: ADC_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_Disable}
  - type: String
    attributes: {id: INTERRUPT_ADC_RESULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc1, value: ADC1_RESRDY_IRQn}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: ADC1_ADC}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: pmsm_foc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: pmsmfoc_ADC}
- type: ElementPosition
  attributes: {x: '171', y: '155', id: adc1}
