format_version: v1.0
type: UniqueComponent
attributes: {id: eic}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: EIC_ASYNCH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '0'}
  - type: Boolean
    attributes: {id: EIC_CHAN_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: 'true'}
  - type: KeyValueSet
    attributes: {id: EIC_CONFIG_SENSE_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: Hex
    attributes: {id: EIC_DEBOUNCEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '4'}
  - type: Boolean
    attributes: {id: EIC_DEBOUNCEN_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: 'true'}
  - type: Hex
    attributes: {id: EIC_EXTINTEO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '4'}
  - type: Boolean
    attributes: {id: EIC_EXTINTEO_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: 'true'}
  - type: Hex
    attributes: {id: EIC_INT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eic, value: '0'}
- type: ElementPosition
  attributes: {x: '430', y: '60', id: eic}
