format_version: v1.0
type: UniqueComponent
attributes: {id: pmsm_foc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: MCPMSMFOC_ADCPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: adc0}
  - type: String
    attributes: {id: MCPMSMFOC_ADCPLIB1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: adc1}
  - type: Integer
    attributes: {id: MCPMSMFOC_ADC_DEP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1'}
  - type: Integer
    attributes: {id: MCPMSMFOC_ADC_MAX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '4095'}
  - type: Float
    attributes: {id: MCPMSMFOC_CL_BANDWIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2000.0'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_DIRECTION_BUTTON}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '94'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_DIRECTION_LED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '55'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_FAULT_LED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '56'}
  - type: Float
    attributes: {id: MCPMSMFOC_ID_KI}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '9.9E-5'}
  - type: Float
    attributes: {id: MCPMSMFOC_ID_KP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.02'}
  - type: Float
    attributes: {id: MCPMSMFOC_IQ_KI}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '9.9E-5'}
  - type: Float
    attributes: {id: MCPMSMFOC_IQ_KP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.02'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_MOTOR_CONNECTION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0'}
  - type: String
    attributes: {id: MCPMSMFOC_PWMPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: tcc0}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_PWM_FAULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_START_BUTTON}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '93'}
  - type: String
    attributes: {id: MCPMSMFOC_X2CScope}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: X2CScope}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: pmsmfoc_ADC}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: adc0, targetAttachmentID: ADC0_ADC}
      - type: TargetAttachment
        attributes: {targetComponentID: adc1, targetAttachmentID: ADC1_ADC}
  - type: DirectDependency
    attributes: {id: pmsmfoc_PWM}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: tcc0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: TCC0_PWM}
  - type: DirectDependency
    attributes: {id: pmsmfoc_X2CSCOPE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: X2CScope}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: x2cScope_Scope}
- type: ElementPosition
  attributes: {x: '395', y: '118', id: pmsm_foc}
