format_version: v1.0
type: UniqueComponent
attributes: {id: pwm0}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: INTR_PWM_FAULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: PWM0_IRQn}
  - type: String
    attributes: {id: PWM_CALLBACK_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: PWM0_CallbackRegister}
  - type: Integer
    attributes: {id: PWM_CH_0_CDTY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '0'}
  - type: KeyValueSet
    attributes: {id: PWM_CH_0_CMR_CALG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '1'}
  - type: Boolean
    attributes: {id: PWM_CH_0_CMR_DTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: Integer
    attributes: {id: PWM_CH_0_CPRD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '3750'}
  - type: Integer
    attributes: {id: PWM_CH_0_DT_DTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '150'}
  - type: Integer
    attributes: {id: PWM_CH_0_DT_DTL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '150'}
  - type: Boolean
    attributes: {id: PWM_CH_0_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: Boolean
    attributes: {id: PWM_CH_0_FAULT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: KeyValueSet
    attributes: {id: PWM_CH_0_FPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '2'}
  - type: Comment
    attributes: {id: PWM_CH_0_FREQ_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 20000.0 Hz ****'}
  - type: Integer
    attributes: {id: PWM_CH_1_CDTY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '0'}
  - type: KeyValueSet
    attributes: {id: PWM_CH_1_CMR_CALG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '1'}
  - type: Boolean
    attributes: {id: PWM_CH_1_CMR_DTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: Integer
    attributes: {id: PWM_CH_1_CPRD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '3750'}
  - type: Integer
    attributes: {id: PWM_CH_1_DT_DTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '150'}
  - type: Integer
    attributes: {id: PWM_CH_1_DT_DTL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '150'}
  - type: Boolean
    attributes: {id: PWM_CH_1_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: Boolean
    attributes: {id: PWM_CH_1_FAULT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: KeyValueSet
    attributes: {id: PWM_CH_1_FPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '2'}
  - type: Comment
    attributes: {id: PWM_CH_1_FREQ_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 20000.0 Hz ****'}
  - type: Boolean
    attributes: {id: PWM_CH_1_SYNCENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: Integer
    attributes: {id: PWM_CH_2_CDTY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '0'}
  - type: KeyValueSet
    attributes: {id: PWM_CH_2_CMR_CALG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '1'}
  - type: Boolean
    attributes: {id: PWM_CH_2_CMR_DTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: Integer
    attributes: {id: PWM_CH_2_CPRD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '3750'}
  - type: Integer
    attributes: {id: PWM_CH_2_DT_DTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '150'}
  - type: Integer
    attributes: {id: PWM_CH_2_DT_DTL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '150'}
  - type: Boolean
    attributes: {id: PWM_CH_2_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: Boolean
    attributes: {id: PWM_CH_2_FAULT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: KeyValueSet
    attributes: {id: PWM_CH_2_FPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '2'}
  - type: Comment
    attributes: {id: PWM_CH_2_FREQ_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 20000.0 Hz ****'}
  - type: Boolean
    attributes: {id: PWM_CH_2_SYNCENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: Boolean
    attributes: {id: PWM_COMP_0_CMPM_CEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: Integer
    attributes: {id: PWM_COMP_0_CMPV_CV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '10'}
  - type: Boolean
    attributes: {id: PWM_COMP_0_ELMR0_CSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: Boolean
    attributes: {id: PWM_FAULT_0_IER1_FCHID}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: 'true'}
  - type: KeyValueSet
    attributes: {id: PWM_FMR_FMOD_INDEX_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '0'}
  - type: Hex
    attributes: {id: PWM_FMR_FMOD_VAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '251'}
  - type: String
    attributes: {id: PWM_GET_PERIOD_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: PWM0_ChannelPeriodGet}
  - type: Hex
    attributes: {id: PWM_IER1_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '65536'}
  - type: Comment
    attributes: {id: PWM_NVIC_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: PWM_OUTPUT_DISABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: PWM0_ChannelOverrideDisable}
  - type: String
    attributes: {id: PWM_OUTPUT_ENABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: PWM0_ChannelOverrideEnable}
  - type: Hex
    attributes: {id: PWM_PH_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: '7'}
  - type: String
    attributes: {id: PWM_PH_U}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: PWM_CHANNEL_0}
  - type: String
    attributes: {id: PWM_PH_V}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: PWM_CHANNEL_1}
  - type: String
    attributes: {id: PWM_PH_W}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: PWM_CHANNEL_2}
  - type: String
    attributes: {id: PWM_SET_DUTY_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: PWM0_ChannelDutySet}
  - type: String
    attributes: {id: PWM_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: PWM0_ChannelsStart}
  - type: String
    attributes: {id: PWM_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm0, value: PWM0_ChannelsStop}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: PWM0_PWM}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: pmsm_foc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: pmsmfoc_PWM}
- type: ElementPosition
  attributes: {x: '166', y: '129', id: pwm0}
