format_version: v1.0
type: UniqueComponent
attributes: {id: uart0}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BAUD_RATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: '115200'}
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart0, value: '81'}
  - type: Integer
    attributes: {id: UART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart0, value: '150000000'}
  - type: Boolean
    attributes: {id: UART_RING_BUFFER_ENABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart0, value: 'false'}
  - type: Boolean
    attributes: {id: USART_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: 'false'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: UART0_UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: X2CScope}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: x2cScopeUartDependency}
- type: ElementPosition
  attributes: {x: '26', y: '302', id: uart0}
