format_version: v1.0
type: UniqueComponent
attributes: {id: pmsm_foc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: MCPMSMFOC_ADCPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: adc0}
  - type: String
    attributes: {id: MCPMSMFOC_ADCPLIB1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: adc1}
  - type: Integer
    attributes: {id: MCPMSMFOC_ADC_DEP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1'}
  - type: Integer
    attributes: {id: MCPMSMFOC_ADC_MAX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '4095'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_ALIGNMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Float
    attributes: {id: MCPMSMFOC_CL_BANDWIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2000.0'}
  - type: Integer
    attributes: {id: MCPMSMFOC_DCBUSV_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '15'}
  - type: Integer
    attributes: {id: MCPMSMFOC_DCBUSV_MODULE}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '1'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_DIRECTION_BUTTON}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '94'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_DIRECTION_LED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '55'}
  - type: Menu
    attributes: {id: MCPMSMFOC_ENCODER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: MCPMSMFOC_ENCODERPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: pdec}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_FAULT_LED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '56'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_MOTOR_CONNECTION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0'}
  - type: Float
    attributes: {id: MCPMSMFOC_OL_END_SPEED}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Float
    attributes: {id: MCPMSMFOC_OL_RAMP_TIME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: MCPMSMFOC_OPEN_LOOP}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PHASEU_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '15'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PHASEU_MODULE}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '1'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PHASEV_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '15'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PHASEV_MODULE}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '1'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_POSITION_FB}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: File
    attributes: {id: MCPMSMFOC_POS_ENCODER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: MCPMSMFOC_POS_ENCODER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: MCPMSMFOC_POS_PLL_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: MCPMSMFOC_POS_PLL_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: MCPMSMFOC_POT_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '15'}
  - type: Integer
    attributes: {id: MCPMSMFOC_POT_MODULE}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '1'}
  - type: String
    attributes: {id: MCPMSMFOC_PWMPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: tcc0}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_PWM_FAULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PWM_PH_U}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '3'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PWM_PH_V}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '3'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PWM_PH_W}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '3'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_START_BUTTON}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '93'}
  - type: String
    attributes: {id: MCPMSMFOC_X2CScope}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: X2CScope}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: pmsmfoc_ADC}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: adc1, targetAttachmentID: ADC1_ADC}
      - type: TargetAttachment
        attributes: {targetComponentID: adc0, targetAttachmentID: ADC0_ADC}
  - type: DirectDependency
    attributes: {id: pmsmfoc_PWM}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: tcc0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: TCC0_PWM}
  - type: DirectDependency
    attributes: {id: pmsmfoc_QDEC}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: pdec}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: PDEC_QDEC}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: DirectDependency
    attributes: {id: pmsmfoc_X2CSCOPE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: X2CScope}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: x2cScope_Scope}
- type: ElementPosition
  attributes: {x: '404', y: '146', id: pmsm_foc}
