format_version: v1.0
type: UniqueComponent
attributes: {id: pdec}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ENCODER_POS_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: PDEC_QDECPositionGet}
  - type: String
    attributes: {id: ENCODER_POS_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: ''}
  - type: String
    attributes: {id: ENCODER_SPEED_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: ''}
  - type: String
    attributes: {id: ENCODER_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: PDEC_QDECStart}
  - type: String
    attributes: {id: ENCODER_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: PDEC_QDECStop}
  - type: Integer
    attributes: {id: PDEC_CC0_ANGULAR}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: PDEC_CC0_REVOLUTION}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '0'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: PDEC_CC1_ANGULAR}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: PDEC_CC1_REVOLUTION}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '0'}
  - type: File
    attributes: {id: PDEC_COUNTER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: PDEC_COUNTER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: PDEC_CTRLA_ANGULAR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '16'}
  - type: Hex
    attributes: {id: PDEC_CTRLA_ANGULAR_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '65535'}
  - type: KeyValueSet
    attributes: {id: PDEC_CTRLA_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '0'}
  - type: Boolean
    attributes: {id: PDEC_CTRLA_PEREN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: 'false'}
  - type: Integer
    attributes: {id: PDEC_CTRLA_REVOLUTION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '0'}
  - type: Hex
    attributes: {id: PDEC_CTRLA_REVOLUTION_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '0'}
  - type: Hex
    attributes: {id: PDEC_EVCTRL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '0'}
  - type: Integer
    attributes: {id: PDEC_FILTER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: File
    attributes: {id: PDEC_HALL_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: PDEC_HALL_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: PDEC_INDEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: Disabled}
  - type: Hex
    attributes: {id: PDEC_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '3'}
  - type: Hex
    attributes: {id: PDEC_PIN_INV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdec, value: '0'}
  - type: File
    attributes: {id: PDEC_QDEC_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: PDEC_QDEC_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: PDEC_QDEC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: PDEC_HALL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectCapability
    attributes: {id: PDEC_QDEC}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: pmsm_foc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: pmsmfoc_QDEC}
- type: ElementPosition
  attributes: {x: '30', y: '239', id: pdec}
