// (c) 2020 Microchip Technology Inc. and its subsidiaries
// Subject to your compliance with these terms, you may use Microchip software and any derivatives exclusively 
// with Microchip products. You’re responsible for complying with 3rd party license terms applicable to your use 
// of 3rd party software (including open source software) that may accompany Microchip software. 
// SOFTWARE IS “AS IS.” NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY 
// IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP 
// BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
// KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR 
// THE DAMAGES ARE FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP’S TOTAL LIABILITY ON ALL CLAIMS RELATED 
// TO THE SOFTWARE WILL NOT EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.

motorName = '${MCPMSMFOC_MOTOR_SEL}';

// Nameplate parameters
MOTOR_WindingConnectionType = '${MCPMSMFOC_MOTOR_CONNECTION}';
MOTOR_RatedVoltageInVolts = ${MCPMSMFOC_RATED_VOLTAGE};
MOTOR_Polepairs = ${MCPMSMFOC_POLE_PAIRS};
MOTOR_NominalRpm = ${MCPMSMFOC_RATED_SPEED}
MOTOR_MaximumRpm = ${MCPMSMFOC_MAX_SPEED}
MOTOR_RatedCurrentInAmps = ${MCPMSMFOC_MAX_MOTOR_CURRENT};

// Electrical parameters
MOTOR_PhaseRsInOhm = ${MCPMSMFOC_R};
MOTOR_PhaseLdInHenry = ${MCPMSMFOC_LD};
MOTOR_PhaseLqInHenry = ${MCPMSMFOC_LQ};
MOTOR_BemfConstInVrmsPerKrpm = ${MCPMSMFOC_BEMF_CONST};

// Mechanical parameters 
MOTOR_InertiaInNmPerSecSqr = ${MCPMSMFOC_ROTOR_INERTIA};
MOTOR_DampingCoeffInNmSecPerRad = ${MCPMSMFOC_VISCOUS_DAMPING};
MOTOR_FrictionTorqueInNm = ${MCPMSMFOC_FRICTION_TORQUE};